# configuration of hyperparameters
online: false
bucket: /gcs/emotions-410912/
model_name: distilbert-base-uncased
hyperparameters:
  batch_size: 16
  num_train_epochs: 1
  learning_rate: 2e-5
  weight_decay: 0.01
